### ISSUE TITLE
The attention map doesn't seem to have anything to do with Angle?

### ISSUE THREAD

**Issue by liguopeng0923** [tudelft-iv/CCVPE#4]
Hi zimin,

I can't understand the means of  [this figure](https://github.com/tudelft-iv/CCVPE/assets/61257834/6099c0e7-f204-49fd-ac7c-fef390bcba43)

The attention map doesn't seem to have anything to do with Angle?

Best,
Guopeng.

**Comment by ZiminXia** [comment]
Hi Guopeng,

This figure shows how the ground image matches to the aerial image at the assumed orientations. This is more for high-level intuition.
For your understanding, I updated two videos "matching_score_different_ori_channel" in /figures. In the video, I selected the orientation channels corresponding to North, East, South, and West in the satellite view, and showed the matching scores (at the coarsest and finest levels) between a rotated ground image and satellite feature at those orientation channels.

As the videos demonstrate, when the orientation of the ground view changes, the matching score patterns re-occur in different orientation channels. At the beginning the ground image views toward the North, and then moves to the West, South, and East, you can see the "north matching score map" at 0 seconds, re-occurs at the west at 3 seconds, and so forth.

This shows that different orientation channels encode orientation-specific scene representation. When only the orientation of the ground view changes (no content change, because the panorama always covers the 360-degree scene), we see the aerial feature being matched in the same way at different orientation channels.

Hope this resolves your question.

Best regards,
Zimin

**Comment by liguopeng0923** [comment]
Thank you very very much!!

I have no problems.
